version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "7000:7000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend

volumes:
  mongo_data:
